- hosts: all
  tasks:
  - name: Ansible arithemtic power filter example
    debug:
      msg: "{{ 3|pow(3)}}"
  - name: Ansible math power filter example
    debug:
      msg: "{{ 27|root(3)}}"
  - name: Ansible round filter example - output 30
    debug:
      msg: "{{ 29.7 | round}}"

  - name: Ansible round number with precision specified example - output 29.1
    debug:
      msg: "{{ 29.094 | round(1,'common')}}"

  - name: Floor round operation with precision example - output 29.0
    debug:
      msg: "{{ 29.094 | round(1,'floor')}}"

  - name: Ceil round operation with precision specified example - output 29.1
    debug:
      msg: "{{ 29.094 | round(1,'ceil')}}"
